version: '3'
services:
  app:
    build: .
    container_name: my-app  # фиксированное имя контейнера для приложения
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "0.0.0.0:8080"
      POSTGRES_USERNAME: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_HOST: "db"  # Используйте имя сервиса 'db'
      POSTGRES_PORT: "5432"
      POSTGRES_DATABASE: "mydb"
      POSTGRES_CONN: "postgresql://myuser:mypassword@db:5432/mydb"
    depends_on:
      - db

  db:
    image: postgres
    container_name: my-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
