import os

SERVER_ADDRESS = os.getenv("SERVER_ADDRESS", "0.0.0.0:8080")
host, port = SERVER_ADDRESS.split(":")
POSTGRES_CONN = os.getenv("POSTGRES_CONN")

POSTGRES_USERNAME = os.getenv("POSTGRES_USERNAME")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT", "5432")
POSTGRES_DATABASE = os.getenv("POSTGRES_DATABASE")

DATABASE_URL = f"postgresql://{POSTGRES_USERNAME}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:" \
               f"{POSTGRES_PORT}/{POSTGRES_DATABASE}"
